### PR TITLE
Update TaskHub Website

### LINKED ISSUE #37: Update Project Website
A Week 7 task

### PR DESCRIPTION
**Pull request by Chandan8186**
Fix #37

### CODE REVIEW

**Review by antonTan96 — COMMENTED** [review]
Should there be changes in `docs\_sass\minima\_base.scss`?

**Comment by rayyan35p** [comment]
> Should there be changes in `docs\_sass\minima\_base.scss`?

The header was changed from "AB-3" to "TaskHub" actually, but for some reason our page right now still shows "AB-3" on the header.

**Comment by Chandan8186** [comment]
Yup I had realised that @rayyan35p when I only changed the scss file in a previous PR (which is already merged with master). So @antonTan96 this PR makes additional changes that should fix the title

**Review by rayyan35p — APPROVED** [review]
Changes seem to be correct, lgtm.

**Pull request merged**
