### PR TITLE
Add additional JUnit tests for listP

### PR DESCRIPTION
**Pull request by Chandan8186**
This PR aims to bring necessary JUnit test(s) for the `listP` command. As of now, only one test is required to cover the `listP` command. If there are tests that need to be included for other commands/methods, it will be best to include them in their relevant PRs.

### CODE REVIEW

**Review by antonTan96 — APPROVED** [review]
LGTM!

**Comment by aslam341** [comment]
@Chandan8186 why is there a decrease in code coverage here? As far as I can tell, you added a test case, but codecov says the coverage decreased.

**Comment by Chandan8186** [comment]
@aslam341 it seems odd, the codecov should be increasing, but I'll try to merge the latest master commit into this PR

**Comment by Chandan8186** [comment]
Since this PR contains only one small change, I have made the change in another relevant PR #110. I will close this PR for now.

**Pull request closed without merging**
