### PR TITLE
Add missing commands into help Window

### LINKED ISSUE #148: Missing several Commands in quick help window
The missing commands are the follows:
`dl`
`markP`
`unmarkP`
`priorityP`
`markT`
`unmarkT`

### PR DESCRIPTION
**Pull request by antonTan96**
Close #148 
After this PR, commands in the help window will be shown in the following order:
### General Commands
* help
* list
* clear
* exit

### Employee Commands
* addE
* editE
* deleteE
* listE
* findE

### Project Commands
* addP
* editP
* deleteP
* markP
* unmarkP
* dlP
* priorityP
* listP
* findP

### Task Commands
* addT
* deleteT
* markT
* unmarkT
* sortT

### Assignment Commands
* assignP
* unassignP
* assignT
* unassignT

Additionally, the help window is also changed to fit the entire window, and is now resizable.

image

### CODE REVIEW

**Comment by Chandan8186** [comment]
@antonTan96 To solve the white space issue, in `HelpWindow.fxml`, you could:
1. In the ScrollPane element, add `fitToWidth="true"`
2. In the outermost VBox element, add `HBox.hgrow="ALWAYS"`

image

**Review by Chandan8186 — APPROVED** [review]
LGTM!

**Review by timleow — APPROVED** [review]
LGTM

**Review by Chandan8186 — CHANGES_REQUESTED** [review]
Apologies for the earlier approval, LGTM except for a couple of things:

- There is an additional `list` command that lists out all employees and projects
- The `findE` description could be made similar to that of `findP` i.e. the following could be added: "Additionally, it shows only the projects that these employees are under."

Also, this is up to you but maybe the order of commands could be rearranged? e.g. grouping markT and unmarkT together

**Review by rayyan35p — COMMENTED** [review]
As per what Chandan said, the `list` for "Listing All Employees and Projects" command is not included. If possible, try to group similar commands together as well.

**Review by Chandan8186 — APPROVED** [review]
LGTM

**Pull request merged**
